In [ ]:
Machine Learning 
Machine Learning is a way for computers to learn from data and making decisions or predictions without being explicitly programmed for every task.
Instead of following a set of instructions, the computer uses pattern in the data to improve it's performance over time.
It is a subset of Arificial Intelligence(AI).
Deep Learning(DL) is the subset of Machine Learning(ML).
Author of Machine Learning is Arthur Samuel.

In [ ]:
How Does Machine Learning Work ?
A Machine Learning system build the prediction models,learns from previous data and predicts the output for new data.
The Amount of Data helps a better model that accurately predicts the better output.
    
Steps of Working in Machine Learning:
1) First step is to learn the previous Input past data.
2) then we need to train the data
3) Then we consider one of any Machine Learning algorithms and learn from data again
4) Then we need to build the logic models for to predict the output for new data.
5) Then the Result will comes that means Output.

In [ ]:
Features of Machine Learning
1) Machine Learning uses data to detect various Patterns in the given dataset.
2) It can learn from past data and it imporoves the performance of data automatically.
3) it is a data-driven technology
4) Machine Learning is same as data mining as it also deals with huge amount of data.

In [ ]:
Need for Machine Learning
1) Rapid Increment for Production of Data.
2) Solving complex problems, which is difficult for humans.
3) Decision Making in various sectors including finance sector.
4) Finding Hidden Patterns and extract usefuful information from data.

In [ ]:
classification of Machine Learning
Machine Learning can be classified into three types. They are:
1) Supervised Learning
2) Unsupervised Learning
3) Reinforcement Learning

In [ ]:
Supervised Learning
In Supervised Learning, sample labelled data was provided for machine learning for training and the system then predicts the output
based on the training data.
Supervised learing is also known as labelled data.
The System uses labelled data to build a model that understands the datasets and learn about each one.
After the training and processing are done, we test the model with sample data to see it if an accurately predict the output.

Supervised Learning is also classified into two types. They are:
1) Classification
2) Regression

In [ ]:
Unsupervised Learning
Unsupervised Learning is a learning method in which a machine learns without any supervision.
that means Unsupervised Learning is learns the data without labels,classified or categorized and the algorithm needs to act on the data without 
any supervision.

Unsupervised Learning is also classified into two types. They are:
1) Clustering
2) Association

In [ ]:
Reinforcement Learning
Reinforcement Learning is also known as Feedback based Learning. In which a learning agent gots a reward for right actions and also gots penalty 
for wrong actions. so it depends on the feedback and incase agent got any penalty he would improve his performance and agent got reward because 
improving his performance.

In [ ]:
There is another classification of supervised Learning
that is Semi-Supervised Learning.
Semi-Supervised Learning is a combination of Supervised Learning and Unsupervised Learning.
It gives both Labelled data and unlabelled data but it provides maximum unlabelled data.

In [ ]:
Application of Machine Learning
1) Image Recognition
2) Speech Recogniton
3) Traffic Prediction
4) Online Fraud Detection
5) Automatic Language Translator
6) Self-driven cars
7) Product recommendations
8) Email spam and malware filtering
9) stock market trading
10) Virtual Personal Assistant
11) Medical Diagnosis

In [ ]:
Machine Learning Life-Cycle
1) Gathering Data
2) Data Preparation
3) Data Wragling
4) Analyze Data
5) Train Model
6) Test Model
7) Deployment

In [ ]:
Gathering Data
The goal of the Gathering data is identify and obtain all data related problems.
steps are
1) Identify the data from various data sources.
2) collecting the data from various data sources like file,databases,internet or mobile devices etc.
3) Integrate the data obtained from different sources. Integrated means combing data from souce to another souce.

In [ ]:
Data Preparation
Data Preparation is a step where we put our data in a suitable place and prepare it to use for Machine Learning Trainin by data exploration and
data preprocessing.

In [ ]:
Data Wragling
Data Wragling is the process of cleaning and converting the raw data into usable format.
Missing Values
Duplicate Data
Invalid Data
Noise

In [ ]:
Data Analysis
1) Selection of Analytical Techniques
2) Building Models
3) Review the Result

In [ ]:
Train Model is used to train our model to improve its performance for better outcome of the Problem.
Test Model is used to check the accuracy of our model by providing a test dataset to it.
Deployment Model is used to simply check the performance was improved or not.

In [ ]:
Data PreProcessing is a process of making raw data and making it suitable for a machine learning model. Especially Data Preprocessing is used for
cleaning the Data.

In [ ]:
why do we need Data PreProcessing
1) Gathering the Dataset
2) Importing Libraries
3) Importing Dataset
4) Finding the Missing Data
5) Encoding the categorical data
6) Splitting dataset into training and test set
7) Feature Scaling

In [ ]:
Gathering the Dataset
we Gather the Dataset like this
a={'names':np.random.choice(['Sai Balaji','chaithanya','Upendra'],size=100),'id':(np.random.randint(1,100,size=100)),
   'position':np.random.choice(['Fresher','Tester','Developer'],size=100)}
b=pd.DataFrame(a)

In [ ]:
Above small code depicts about to give some data to the dataset.
but in that code there is np and pd
what is that?
Here np is Numpy and pd is Pandas. Both Numpy and Pandas are Libraries.
but i need to save the dataset into particular one. so i need to save the dataset in .csv file

csv- comma separated values .t is a file format which allows us to save the tabular data, such as spreadsheets. 
It is useful for huge datasets and can use these datasets in programs.

In [ ]:
import pandas as pd
import numpy as np
a={'names':np.random.choice(['Sai Balaji','chaithanya','Upendra'],size=100),
   'id':(np.random.randint(1,100,size=100)),'position':np.random.choice(['Fresher','Tester','Developer'],size=100)}
b=pd.DataFrame(a)
b.to_csv('output.csv')

In [ ]:
from the above, we can gathering the datset, importing libraries like numpy as np and pandas as pd and importing the dataset by csv.

In [ ]:
Finding the Missing Data
Way to handle the missing data
1) By Deleting the Specific Row
2) By calculating mean

In [1]:
from sklearn.preprocessing import imputer
a=imputer(missing_values='NaN',strategy='mean',axis=1)
a=a.fit(x[:,1:3])
x[:,1:3]=a.transform(x[:,1:3])

ImportError: cannot import name 'imputer' from 'sklearn.preprocessing' (C:\Users\INTEL 89\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\preprocessing\__init__.py)

In [5]:
import numpy as np
from sklearn.impute import SimpleImputer
x = np.array([[1, 2, np.nan],
              [4, np.nan, 6],
              [7, 8, 9]])
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
a = imputer.fit_transform(x[:, 1:3])
print(a)

[[2.  7.5]
 [5.  6. ]
 [8.  9. ]]

In [ ]:
Encoding the categorical data
Since machine learning model completely works on mathematics and numbers, but if our dataset would have a categorical variable,
then it may create trouble while building the model. So it is necessary to encode these categorical variables into numbers.

In [18]:
from sklearn.preprocessing import LabelEncoder
a=LabelEncoder()
x[:,0]=a.fit_transform(x[:,0])
print(x)

[[ 0.  2. nan]
 [ 1. nan  6.]
 [ 2.  8.  9.]]

In [25]:
import numpy as np
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
x = np.array([['red', 2, 3],
              ['green', 5, 6],
              ['blue', 8, 9]])
a = LabelEncoder()
x[:, 0] = a.fit_transform(x[:, 0])
print("After Label Encoding:")
print(x)
ct = ColumnTransformer([('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = ct.fit_transform(x)
print("After OneHot Encoding:")
print(x)

After Label Encoding:
[['2' '2' '3']
 ['1' '5' '6']
 ['0' '8' '9']]
After OneHot Encoding:
[['0.0' '0.0' '1.0' '2' '3']
 ['0.0' '1.0' '0.0' '5' '6']
 ['1.0' '0.0' '0.0' '8' '9']]

In [ ]:
Splitting the dataset into train set and test set

In [3]:
import pandas as pd
import numpy as np
a=pd.read_csv('Output.csv')
display(a)

         names  id   position Blood Group  marks
0      Upendra  32  Developer          B+     50
1      Upendra   6  Developer          B+     50
2   chaithanya  86  Developer          B+     50
3   Sai Balaji  31  Developer          B-    100
4      Upendra  18  Developer          B-    100
..         ...  ..        ...         ...    ...
95  chaithanya  72    Fresher          O+    100
96     Upendra  62     Tester          O+     50
97  Sai Balaji  66  Developer          B-    100
98     Upendra  44  Developer          B-     75
99     Upendra   3  Developer          B+    100

[100 rows x 5 columns]

In [4]:
from sklearn.model_selection import train_test_split  
import pandas as pd
x=a[['names','id']]
y=a['marks']
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 0.2, random_state=0)
display(x_train)
display(y_train)

         names  id
43  chaithanya   1
62     Upendra  16
3   Sai Balaji  31
71  chaithanya  79
45     Upendra  56
..         ...  ..
96     Upendra  62
67  chaithanya  29
64  Sai Balaji  88
47  Sai Balaji  53
44     Upendra  34

[80 rows x 2 columns]

43    100
62     75
3     100
71    100
45     75
     ...
96     50
67     50
64     75
47     75
44    100
Name: marks, Length: 80, dtype: int64

In [ ]:
7) Feature Scaling
Feature scaling is the final step of data preprocessing in machine learning. 
It is a technique to standardize the independent variables of the dataset in a specific range. 
In feature scaling, we put our variables in the same range and in the same scale so that no any variable dominate the other variable.

In [17]:
from sklearn.model_selection import train_test_split 
from sklearn.preprocessing import StandardScaler
import pandas as pd
a=pd.read_csv('Output.csv')
x=a[['names','id']]
y=a['marks']
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 0.2, random_state=0)
display(x_train)
display(y_train)
a=StandardScaler()
x_train_numeric = x_train[['id']]
x_test_numeric=x_test[['id']]
x_train=a.fit_transform(x_train_numeric)
x_test=a.fit_transform(x_test_numeric)
print(x_train)
print('x_test')
print(x_test)

         names  id
43  chaithanya   1
62     Upendra  16
3   Sai Balaji  31
71  chaithanya  79
45     Upendra  56
..         ...  ..
96     Upendra  62
67  chaithanya  29
64  Sai Balaji  88
47  Sai Balaji  53
44     Upendra  34

[80 rows x 2 columns]

43    100
62     75
3     100
71    100
45     75
     ...
96     50
67     50
64     75
47     75
44    100
Name: marks, Length: 80, dtype: int64

[[-1.68742987]
 [-1.16915092]
 [-0.65087198]
 [ 1.00762065]
 [ 0.21292627]
 [ 0.45478978]
 [-1.27280671]
 [-1.61832601]
 [ 0.04016662]
 [-0.92728742]
 [ 1.45679574]
 [ 1.00762065]
 [-0.4435604 ]
 [ 0.55844557]
 [ 1.38769188]
 [ 1.35313995]
 [-1.16915092]
 [ 0.35113399]
 [ 0.86941293]
 [-0.96183935]
 [-1.51467022]
 [-1.68742987]
 [ 0.00561469]
 [-1.68742987]
 [-1.10004706]
 [ 0.52389364]
 [ 0.14382241]
 [ 1.04217258]
 [-1.27280671]
 [ 1.56045153]
 [-1.61832601]
 [-0.71997584]
 [-0.61632005]
 [ 1.56045153]
 [ 0.04016662]
 [-0.37445654]
 [ 0.48934171]
 [ 1.62955539]
 [ 0.55844557]
 [-1.10004706]
 [ 0.97306872]
 [ 0.55844557]
 [-0.23624882]
 [ 0.04016662]
 [ 0.55844557]
 [-0.4435604 ]
 [ 0.04016662]
 [-0.06348917]
 [ 1.00762065]
 [ 1.49134767]
 [ 0.48934171]
 [-1.13459899]
 [ 1.04217258]
 [ 0.55844557]
 [-0.20169689]
 [-1.3764625 ]
 [ 1.21493223]
 [ 1.45679574]
 [-1.65287794]
 [ 1.69865925]
 [-0.99639128]
 [ 0.21292627]
 [ 1.38769188]
 [-0.23624882]
 [-0.85818356]
 [-0.65087198]
 [ 1.00762065]
 [ 1.00762065]
 [ 0.86941293]
 [-0.33990461]
 [ 0.28203013]
 [-1.30735864]
 [-1.44556636]
 [-0.54721619]
 [ 0.35113399]
 [ 0.42023785]
 [-0.71997584]
 [ 1.31858802]
 [ 0.10927048]
 [-0.54721619]]
x_test
[[ 0.21755667]
 [ 0.0805131 ]
 [ 0.93703543]
 [ 1.34816615]
 [-0.22783494]
 [-1.11861816]
 [ 1.21112258]
 [-1.15287906]
 [ 1.38242704]
 [ 0.45738292]
 [ 0.21755667]
 [-0.87879191]
 [-1.22140084]
 [ 0.32033935]
 [-0.67322655]
 [-0.09079137]
 [ 1.14260079]
 [-1.90661871]
 [-1.28992263]
 [ 1.24538347]]

In [23]:
import numpy as np
import pandas as pd
a=pd.read_csv('Output.csv')
b=a.iloc[:,0:].values
c=a.iloc[:,:-1].values
from sklearn.impute import SimpleImputer
d=np.array([[1,2,np.nan],[3,np.nan,5],[7,8,9]])
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
e=imputer.fit_transform(d[:,0:4])
print(e)
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.compose import ColumnTransformer
f=np.array([['red',2,3],['green',5,6],['blue',8,9]])
g=LabelEncoder()
f[:,0]=g.fit_transform(f[:,0])
print(f)
ct=ColumnTransformer([('encoder',OneHotEncoder(),[0])],remainder='passthrough')
f=ct.fit_transform(f)
print(f)
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
x=a[['names','id']]
y=a['marks']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
display(x_train)
display(y_train)
h=StandardScaler()
x_train_numeric=x_train[['id']]
x_test_numeric=x_test[['id']]
x_train=h.fit_transform(x_train_numeric)
x_test=h.fit_transform(x_test_numeric)
print("X_train")
print(x_train)
print("X_test")
print(x_test)

[[1. 2. 7.]
 [3. 5. 5.]
 [7. 8. 9.]]
[['2' '2' '3']
 ['1' '5' '6']
 ['0' '8' '9']]
[['0.0' '0.0' '1.0' '2' '3']
 ['0.0' '1.0' '0.0' '5' '6']
 ['1.0' '0.0' '0.0' '8' '9']]

         names  id
55  Sai Balaji  98
88  chaithanya  75
26     Upendra  65
42  chaithanya  50
69  Sai Balaji  10
..         ...  ..
60  chaithanya  92
71  chaithanya  79
14  chaithanya  79
92  Sai Balaji  33
51  Sai Balaji  90

[80 rows x 2 columns]

55     50
88     50
26     75
42     50
69     75
     ...
60     50
71    100
14     75
92     50
51     75
Name: marks, Length: 80, dtype: int64

X_train
[[ 1.52470514]
 [ 0.75713812]
 [ 0.42341333]
 [-0.07717386]
 [-1.41207302]
 [ 0.42341333]
 [ 0.92400052]
 [ 0.32329589]
 [ 0.25655093]
 [-1.67905286]
 [ 0.39004085]
 [ 0.02294358]
 [-0.51101609]
 [-0.04380138]
 [-0.87811336]
 [ 1.4245877 ]
 [-0.31078121]
 [-0.71125096]
 [ 1.49133266]
 [ 1.39121522]
 [ 0.92400052]
 [ 1.4245877 ]
 [-0.44427113]
 [ 0.65702068]
 [ 1.22435283]
 [ 0.39004085]
 [ 1.25772531]
 [-1.04497575]
 [-1.21183815]
 [ 0.52353077]
 [-1.64568038]
 [-0.71125096]
 [ 0.05631606]
 [-1.31195559]
 [ 1.4245877 ]
 [-0.9782308 ]
 [-1.31195559]
 [ 1.19098035]
 [-1.34532807]
 [ 1.35784275]
 [ 0.25655093]
 [-1.64568038]
 [ 1.55807762]
 [-1.71242534]
 [-0.44427113]
 [-0.77799592]
 [-0.31078121]
 [ 0.45678581]
 [-1.71242534]
 [ 0.45678581]
 [ 0.45678581]
 [-1.71242534]
 [ 0.89062804]
 [ 0.35666837]
 [-0.27740873]
 [-0.04380138]
 [-0.0104289 ]
 [-0.04380138]
 [ 1.32447027]
 [-0.77799592]
 [ 0.75713812]
 [-0.14391882]
 [ 0.12306102]
 [-1.17846567]
 [-1.54556294]
 [-1.14509319]
 [-1.47881798]
 [ 1.12423539]
 [ 0.45678581]
 [ 0.18980598]
 [-1.64568038]
 [-1.01160327]
 [ 0.28992341]
 [-0.04380138]
 [ 1.09086291]
 [ 1.32447027]
 [ 0.89062804]
 [ 0.89062804]
 [-0.644506  ]
 [ 1.25772531]]
X_test
[[-0.57289114]
 [ 0.63115126]
 [-0.33985068]
 [ 0.28159056]
 [-0.57289114]
 [-0.92245184]
 [ 1.67983334]
 [ 1.17491234]
 [ 1.13607226]
 [-0.65057129]
 [-1.27201253]
 [ 0.28159056]
 [-0.92245184]
 [-1.07781214]
 [-0.45637091]
 [-1.19433238]
 [-1.00013199]
 [ 1.95171388]
 [ 1.17491234]
 [ 0.66999133]]

In [ ]:
Supervised Learning
In Supervised Learning, sample labelled data was provided for machine learning for training and the system then predicts the output
based on the training data.
Supervised learing is also known as labelled data.
The System uses labelled data to build a model that understands the datasets and learn about each one.
After the training and processing are done, we test the model with sample data to see it if an accurately predict the output.

Supervised Learning is also classified into two types. They are:
1) Classification
2) Regression

In [ ]:
How Supervised Learning Works:

Working Steps for Supervised Learning:
1) First Determine the Training Dataset.
2) Collect/Gather the labelled training data.
3) Split the dataset into training dataset, test dataset, validation test.
4) Determine the input features of the training dataset, which should have enough knowledge so that the model can accurately predict the output.
5) Determine the suitable algorithm for the model, such as decision trees, random forests, k-nearest neighbors etc.
6) Execute the algorithm on the training dataset. sometimes we need validation sets as the control parameters,which are the subset of the training 
    dataset.
7) Evaluate the accuracy by the given test set.if the model predicts the correct output, which means our model is accurate.

In [ ]:
Types of Supervised Learning
1) Classification
2) Regression

In [ ]:
Classification

Classification algorithms are used when the output variable is categorical, which means there are two classes such as
Yes-No, True-False, Male-Female etc and spam Filtering

Classification algorithms are:
1) Random Forests
2) Decision Trees
3) Support Vector Machines
4) Logistic Regression

In [ ]:
Regression

Regression algorithms are used if the relation between input variable and output variable. it is used for the prediction of continuous variables
such as Weather Forecast, Stock trades etc.

Regression algorithms are:
1) Linear Regression
2) Non-Linear Regression
3) Bayesian Linear Regression
4) Polynomial Regression
5) Regression Trees

In [ ]:
Advantages of Supervised Learning

1) with the help of supervised Learning, the model can predict the output based on the prior experiences.
2) In Supervised Learning, we can have the exact idea about the classes of the objects.
3) It helps us to solve the real world problems like Fraud-Detection and spam filtering etc.

Disadvantages of Supervised Learning
1) Its not possible for handling complex tasks.
2) It cannot the predict the correct output if the test dataset from the training dataset.
3) Training Required lots of computation times.
4) In this model, we need enough knowledge about the classes of the objects.

In [ ]:
Unsupervised Learning
Unsupervised Learning is the learning method which the machine Learns without any Supervison.
that means machine learns without labels, categorical or classified and algorithms need to act on the data without any supervision.
Unsupervised Learning also known as unlabelled data.

Unsupervised Learning is also classified into two types. They are:
1) Clustering
2) Association

In [ ]:
The Goal of Unsupervised Learning is to find the underlying structures of the dataset, group that data according to the similarities
and represents the data in the compressed format.

why we use Unsupervised Learning ?

1) Unsupervised Learning is helpful for finding the insights from the data.
2) Unsupervised Learning is much similar as a human learns by their own experiences, which makes it closer to the real AI.
3) Unsupervised Learning is works on uncategorical and unlabelled data which makes this Unsupervised Learning is important.
4) In Real-world, we do not have input data with the corresponding output so to solve such cases, we need unsupervised Learning.

Working of Unsupervised Learning:

1) First we need to take unlabelled data which means it is not categorical and corresponding outputs also not given.
2) Now this unlabelled input data is fed to the machine learning model in order to train it.
3) Firstly, it will interept the raw data to find hidden patterns from the data and then will apply suitable algorithms such as
    k-Nearest Neighbors and decision trees etc.

In [ ]:
Types of Unsupervised Learning

1) Clustering
2) Association

In [ ]:
Clustering

Clustering is a method of grouping the objects into clusters such that objects with most similarities into a group and has less or no similarities
with the objects into a group. cluster analysis finds the commonalities between the data objects and categorized them as the presence and absence
of those commonalities.

In [ ]:
Association

Association Rule is a Unsupervised Learning method which is used for to find relationships between variables in a large dataset.
it determines the set of items that occur together in the dataset. it makes marketing strategy more effective. such as people who buy x item 
are also tend to purchase Y item. A typical example for association is Market Basket Analysis.

Example : For Suppose we ordered Biriyani in swiggy and also for chilling we ordered some cool Drink.
            x=Biriyani
            y=Limca Drink Bottle

In [ ]:
Unsupervised Learning Algorithms:

1) k-means clustering
2) KNN(k-nearest neighbors)
3) Principle Component Analysis
4) Independent Component Analysis
5) Apriori Algorithm
6) Hierarchical Clustering
7) Neural Networks
8) Singular value Decomposition
9) Anomaly Detection

In [ ]:
Advantages of Unsupervised Learning

1) Unsupervised Learning is used for more complex problems as compared to supervised Learning because in unsupervised learning, we don't use 
    labelled data
2) it is preferable as it is easy to get unlabelled data in comparision to labelled data.

Disadvantages of Unsupervised Learning

1) Unsupervised Learning is intrinsically more difficult than supervised learning as it does not have corresponding output.
2) The Result of unsupervised learning algorithm might be less accurate as input data is not labelled and algorithms do not know the exact output
    in advance.

In [ ]:
Differences between Supervised Learning and Unsupervised Learning
--------------------------------------------------------------------------------------------------------------------------------------------------------
| Supervised Learning                                                 |                      Unsupervised Learning                                     |
--------------------------------------------------------------------------------------------------------------------------------------------------------
|It learns from the labelled data and trains the datset and based on  |It is the learning method which machine learns without any supervision.         |
|the training data it accurately produces the output.                 |that means which not have labelled,categorical and classified values            |
--------------------------------------------------------------------------------------------------------------------------------------------------------
|It is Labelled Data.                                                 | It is unlabelled Data.                                                         |
--------------------------------------------------------------------------------------------------------------------------------------------------------
|It is Categorical which is based on two values like True or False.   | It is uncategorical.                                                           |
--------------------------------------------------------------------------------------------------------------------------------------------------------
|In supervised Learning there are two types classification and        | In Unsupervised Learning there are two types Clustering and Association.       |
| Regression.                                                         |                                                                                |
--------------------------------------------------------------------------------------------------------------------------------------------------------
|The Goal of the supervised learning is to learn from labeled data and|The Goal of the Unsupervised Learning is to find underlying datasets or to find |
| to train the dataset and it accurately produces the output from     |the hidden patterns and group the data into similarities and represents the data|
|Training data.                                                       |in compressed format.                                                           |
--------------------------------------------------------------------------------------------------------------------------------------------------------
|It wants Feedback.                                                   | It doesn't need Feedback.                                                      |
--------------------------------------------------------------------------------------------------------------------------------------------------------
|It Predicts the output.                                              | It finds the hidden patterns from the data.                                    |
--------------------------------------------------------------------------------------------------------------------------------------------------------

In [ ]:
Regression Analysis in Machine Learning

Regression analysis is a stastical method to model the relationship between the dependent(target) and independent(predictor) with one or more
independent variable.